name: vim
channels:
    - defaults
    # - anaconda
dependencies:
    - nodejs>=14.14 # For CoC.nvim
    - jedi
    - pip
    - pip:
        - pynvim
    #     - jedi # For Python autocompleters relying on Jedi
